# Generated by Django 5.2.7 on 2025-11-09 22:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clientes/')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_cliente', models.CharField(choices=[('directo', 'Cliente Directo'), ('final', 'Cliente Final')], default='directo', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_sitio', models.CharField(default='TK REDLINE SPA', max_length=200)),
                ('descripcion_sitio', models.TextField(blank=True)),
                ('palabras_clave', models.TextField(blank=True, help_text='Palabras clave separadas por comas')),
                ('logo_footer', models.ImageField(blank=True, null=True, upload_to='config/')),
                ('fondo_global', models.ImageField(blank=True, help_text='Imagen de fondo global del sitio', null=True, upload_to='config/')),
                ('telefono_footer', models.CharField(blank=True, max_length=20)),
                ('email_footer', models.EmailField(blank=True, max_length=254)),
                ('direccion_footer', models.TextField(blank=True)),
                ('redes_sociales', models.JSONField(blank=True, default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuraciones del Sitio',
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('asunto', models.CharField(max_length=300)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='TK REDLINE SPA', max_length=200)),
                ('slogan', models.CharField(default='SOLUCIONES EFICIENTES', max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('mision', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('valores', models.TextField(blank=True)),
                ('direccion', models.CharField(default='C. Carlos Antúnez 2025, Piso 9-904 – PROVIDENCIA – Santiago de Chile', max_length=300)),
                ('telefono', models.CharField(default='+56 9 3494 9214', max_length=20)),
                ('email_principal', models.EmailField(default='mlujan@tekon-rl.cl', max_length=254)),
                ('email_secundario', models.EmailField(blank=True, max_length=254, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='empresa/')),
                ('imagen_fondo_hero', models.ImageField(blank=True, help_text='Imagen de fondo para la sección hero de la página principal', null=True, upload_to='empresa/')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipo/')),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miembro del Equipo',
                'verbose_name_plural': 'Equipo',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('cliente', models.CharField(max_length=200)),
                ('alcance', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('destacado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('icono', models.FileField(blank=True, help_text='Archivo SVG del icono del servicio', null=True, upload_to='servicios/icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicios/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
