# Generated by Django 5.2.7 on 2025-10-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='imagen_fondo_hero',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección hero de la página principal', null=True, upload_to='empresa/'),
        ),
    ]
