# Generated by Django 5.2.7 on 2025-11-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_proyecto_cliente_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='socio',
            field=models.BooleanField(default=False, verbose_name='Socio'),
        ),
    ]
