# Generated by Django 5.2.7 on 2025-11-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_equipo_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='destacado',
            field=models.BooleanField(default=False, help_text='Marcar si el cliente debe aparecer en listados destacados o selecciones.'),
        ),
    ]
