# Generated by Django 5.2.7 on 2025-11-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_cliente_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='puntos_importantes',
            field=models.TextField(blank=True, help_text='Listado opcional (separado por saltos de línea) de hitos a mostrar en clientes destacados.'),
        ),
    ]
