# Generated by Django 5.2.7 on 2025-11-10 13:21

from django.db import migrations, models


def set_cliente_order(apps, schema_editor):
    Cliente = apps.get_model('empresa', 'Cliente')
    for index, cliente in enumerate(Cliente.objects.order_by('nombre'), start=1):
        cliente.orden = index
        cliente.save(update_fields=['orden'])


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_cliente_puntos_importantes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(set_cliente_order, migrations.RunPython.noop),
    ]
