# Generated by Django 5.2.7 on 2025-11-10 14:01

import django.db.models.deletion
from django.db import migrations, models


def bootstrap_sites(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Empresa = apps.get_model('empresa', 'Empresa')
    ConfiguracionSitio = apps.get_model('empresa', 'ConfiguracionSitio')

    tekon_site, _ = Site.objects.update_or_create(
        domain='tekon-rl.cl', defaults={'name': 'Tekon RL'}
    )
    Site.objects.update_or_create(
        domain='redlinegs.com', defaults={'name': 'Redline GS'}
    )

    Empresa.objects.filter(site__isnull=True).update(site=tekon_site)
    ConfiguracionSitio.objects.filter(site__isnull=True).update(site=tekon_site)


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_alter_cliente_options_cliente_orden'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='site',
            field=models.OneToOneField(blank=True, help_text='Sitio/dominio asociado a esta configuración.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_sitio', to='sites.site'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='site',
            field=models.OneToOneField(blank=True, help_text='Sitio/dominio al que pertenece esta empresa.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='sites.site'),
        ),
        migrations.RunPython(bootstrap_sites, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='configuracionsitio',
            name='site',
            field=models.OneToOneField(help_text='Sitio/dominio asociado a esta configuración.', on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_sitio', to='sites.site'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='site',
            field=models.OneToOneField(help_text='Sitio/dominio al que pertenece esta empresa.', on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='sites.site'),
        ),
    ]
