# Generated by Django 5.2.7 on 2025-11-10 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_configuracionsitio_site_empresa_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='logo_svg',
            field=models.FileField(blank=True, help_text='Archivo SVG monocromático que aprovecha currentColor.', null=True, upload_to='config/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
